name: Fake bug report
description: File a bug report
title: Describe the problem
labels: [bug]
body:
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Target Platforms
      description: Select the platform(s) that you are rendering on
      multiple: true
      options:
        - NodeJS
        - iOS
        - Android
        - WPF
        - UWP
        - Other
  - type: dropdown
    attributes:
      label: Target Platform Version
      description: What SDK version are you building for?
      options:
        - "10.0.15063"
        - "10.0.16299"
        - "10.0.19041"
  - type: dropdown
    attributes:
      label: Target Device(s)
      description: What device(s) are you targeting?
      multiple: true
      options:
        - "Desktop"
        - "Xbox"
        - "HoloLens"
  - type: dropdown
    attributes:
      label: Visual Studio Version
      description: Which version of Visual Studio are you using?
      options:
        - "Visual Studio 2017"
        - "Visual Studio 2019"
  - type: dropdown
    attributes:
      label: Build Configuration
      description: Which build configuration are you running?
      options:
        - "Debug"
        - "DebugBundle"
        - "Release"
        - "ReleaseBundle"